//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameAndChill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Game
    {
        public int UserID { get; set; }
        public int GameID { get; set; }
        public bool IsLike { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
